rootDir: core3
outDir: core3/plz-out/gen
manage:
  rules:
    - js_library
    - ops_app_mocha
    - ops_app_jest
    - yarn_script
    - css_library
  fields:
    - name
    - src
    - srcs
    - deps
    - visibility
    - test_only
    - labels
    - entry
  schema:
    create_component_mocha:
      srcs:
        - value: entry
          as: string
    css_library:
      srcs:
        - srcs
        - value: srcs
          as: glob
        - value: src
          as: string
    design_system_jest:
      srcs:
        - value: entry
          as: string
    js_library:
      name:
        - value: name
          as: string
      srcs:
        - srcs
        - value: src
          as: string
        - value: srcs
          as: glob
      deps:
        - value: deps
          as: array
      visibility:
        - value: visibility
          as: array
    yarn_script:
      srcs:
        - value: outs
          as: array
      visibility:
        - value: visibility
          as: array
    ops_app_jest:
      srcs:
        - value: entry
          as: string
    ops_app_mocha:
      srcs:
        - value: entry
          as: string
        - value: srcs
          as: glob
    genrule:
      srcs:
        - outs
match:
  module: .*?\.(js|jsx|ts|tsx|scss)$
  test: .*?\.(spec|test)\.(js|jsx|ts|tsx)$
log:
  - trace
  - debug
  - info
  - warn
  - error
excludeNodeModules: true
enablePropagation: false
onCreate:
  fileExtname: plz
  fileHeading: |-
    This is an onCreate file heading
    It even handles multiple lines!

    And double lines...
  module:
    name: js_library
    explicitDeps: false
    omitEmptyFields: true
    initialVisibility:
      - PUBLIC
    globMatchers:
      include:
        - '**/*.js'
        - '**/*.ts'
        - '**/*.jsx'
        - '**/*.tsx'
      exclude:
        - '**/*.spec.js'
        - '**/*.spec.ts'
        - '**/*.spec.jsx'
        - '**/*.spec.tsx'
  test:
    name: ops_app_jest
    subinclude:
      - //vault/admin_app/apps/ops:ops_app_jest
    explicitDeps: false
    omitEmptyFields: true
    globMatchers:
      include:
        - '**/*.spec.js'
        - '**/*.spec.ts'
        - '**/*.spec.jsx'
        - '**/*.spec.tsx'
      exclude:
        - '**/some/excludeable/file.spec.js'
        - '**/some/excludeable/file.spec.ts'
        - '**/some/excludeable/file.spec.jsx'
        - '**/some/excludeable/file.spec.tsx'
onUpdate:
  fileHeading: |-
    This is an onUpdate module file heading
    It even handles multiple lines!
  module:
    omitEmptyFields: true
  test:
    omitEmptyFields: true
