rootDir: core3
outDir: core3/plz-out/gen
manage:
  rules:
    - js_library
    - ops_app_mocha
    - ops_app_jest
    - yarn_script
    - css_library
  schema:
    filegroup:
      srcs:
        - srcs
        - value: srcs
          as: glob
    create_component_mocha:
      srcs:
        - value: entry
          as: string
    css_library:
      srcs:
        - srcs
        - value: src
          as: string
        - value: srcs
          as: glob
    design_system_jest:
      srcs:
        - value: entry
          as: string
    js_library:
      name:
        - value: name
          as: string
      srcs:
        - srcs
        - value: src
          as: string
        - value: srcs
          as: glob
      deps:
        - value: deps
          as: array
      visibility:
        - value: visibility
          as: array
    yarn_script:
      srcs:
        - value: outs
          as: array
      visibility:
        - value: visibility
          as: array
    ops_app_jest:
      srcs:
        - value: entry
          as: string
    ops_app_mocha:
      srcs:
        - value: entry
          as: string
    workspace_mocha:
      srcs:
        - value: entry
          as: string
    genrule:
      srcs:
        - outs
  knownTargets:
    'instances/feature_flags/ops_dashboard.js': //instances/feature_flags/ops_dashboard
match:
  module: .*?\.(js|jsx|ts|tsx|css|scss|json)$
  fixture: .*?\.(mockData)\.(js|jsx|ts|tsx)$
  test: .*?\.(spec|test)\.(js|jsx|ts|tsx)$
log:
  - trace
  - debug
  - info
  - warn
  - error
excludeNodeModules: true
enablePropagation: false
onCreate:
  fileExtname: plz
  fileHeading: |-
    This is an onCreate file heading
    It even handles multiple lines!

    And double lines...
  module:
    name: js_library
    targetFormat: <filename>_module
    explicitDeps: false
    omitEmptyFields: true
    initialVisibility:
      - PUBLIC
    globMatchers:
      include:
        - '**/*.js'
        - '**/*.ts'
        - '**/*.jsx'
        - '**/*.tsx'
      exclude:
        - '**/*.spec.*'
        - '**/*.mockData.*'
  fixture:
    name: js_library
    targetFormat: <firstname>_fixture
    explicitDeps: true
    omitEmptyFields: false
    initialVisibility:
      - PUBLIC
    testOnly: true
  test:
    name: ops_app_jest
    targetFormat: <firstname>_test
    subinclude:
      - //vault/admin_app/apps/ops:ops_app_jest
    explicitDeps: false
    omitEmptyFields: true
    globMatchers:
      include:
        - '**/*.spec.js'
        - '**/*.spec.ts'
        - '**/*.spec.jsx'
        - '**/*.spec.tsx'
      exclude:
        - '**/some/excludeable/file.spec.*'
onUpdate:
  fileHeading: |-
    This is an onUpdate module file heading
    It even handles multiple lines!
  module:
    omitEmptyFields: true
  fixture:
    omitEmptyFields: true
  test:
    omitEmptyFields: true
    subinclude:
      - //vault/admin_app/apps/ops:ops_app_jest
ignore:
  paths:
    - '**/proto/*'
    - '**/plz-out/*'
    - '**/webpack.{production,test,development}.*'
    - vault/admin_app/apps/ops/src/myTestFolder/myIgnoredDirectory/*
  module:
    paths:
      - '**/proto/*'
      - '**/plz-out/*'
      - '**/webpack.{production,test,development}.*'
      - vault/admin_app/apps/ops/src/myTestFolder/myIgnoredDirectory/*
      - vault/admin_app/apps/ops/src/myTestFolder/myOnlyIgnoreModuleDirectory/*
    targets:
      - //vault/admin_app/apps/common/types:query_types
  fixture:
    targets:
      - //vault/admin_app/apps/common/types:enum_types
  test:
    targets:
      - //vault/admin_app/apps/common/types:enum_types
