manage:
  rules:
    - js_library
    - ops_app_mocha
    - ops_app_jest
    - yarn_script
    - css_library
  fields:
    - name
    - src
    - srcs
    - deps
    - visibility
    - test_only
    - labels
    - entry
  schema:
    css_library:
      srcs:
        - srcs
        - value: src
          as: string
    js_library:
      name:
        - value: name
          as: string
      srcs:
        - srcs
        - value: src
          as: string
      deps:
        - value: deps
          as: array
      visibility:
        - value: visibility
          as: array
    yarn_script:
      srcs:
        - value: outs
          as: array
      visibility:
        - value: visibility
          as: array
    ops_app_jest:
      srcs:
        - value: entry
          as: string
    ops_app_mocha:
      srcs:
        - value: entry
          as: string
    genrule:
      srcs:
        - outs
match:
  module: .*?\.(js|jsx|ts|tsx|scss)$
  test: .*?\.(spec|test)\.(js|jsx|ts|tsx)$
log:
  - trace
  - debug
  - info
  - warn
  - error
paths:
  '@plz/*':
    - ./*
    - ./plz-out/gen/*
  '@muistyled-engine':
    - '@mui/styled-engine-sc'
excludeNodeModules: true
enablePropagation: false
onCreate:
  fileExtname: plz
  fileHeading: |-
    This is an onCreate file heading
    It even handles multiple lines!

    And double lines...
  module:
    name: js_library
    explicitDeps: true
    omitEmptyFields: true
    initialVisibility:
      - PUBLIC
    testOnly: false
  test:
    name: ops_app_jest
    subinclude:
      - //vault/admin_app/apps/ops:ops_app_jest
    explicitDeps: true
    omitEmptyFields: true
onUpdate:
  fileHeading: |-
    This is an onUpdate module file heading
    It even handles multiple lines!
  module:
    omitEmptyFields: true
    subinclude: []
  test:
    omitEmptyFields: true
